table tbl_tools
	lineageTag: 79aca26a-27e1-4557-a36b-ff0b1f8d4611

	column tool_id
		dataType: int64
		formatString: 0
		lineageTag: ce51b34f-6d7f-4065-a02f-2423844c976f
		summarizeBy: none
		sourceColumn: tool_id

		annotation SummarizationSetBy = Automatic

	column tool_group_id
		dataType: int64
		formatString: 0
		lineageTag: 53c6ece9-8fc0-49c6-8ea3-a9b989d6f6ee
		summarizeBy: none
		sourceColumn: tool_group_id

		annotation SummarizationSetBy = Automatic

	column tool_display_name
		dataType: string
		lineageTag: e40db5e0-4f60-4c28-aed2-8ca02822bf8b
		summarizeBy: none
		sourceColumn: tool_display_name

		annotation SummarizationSetBy = Automatic

	column overall_proficiency_level
		dataType: int64
		formatString: 0
		lineageTag: 614ab791-1083-4bae-971b-99a68ddda9dc
		summarizeBy: none
		sourceColumn: overall_proficiency_level

		annotation SummarizationSetBy = Automatic

	column tool_sort_key
		dataType: int64
		formatString: 0
		lineageTag: c190080f-bccb-4d1b-bece-33c19bdee4de
		summarizeBy: none
		sourceColumn: tool_sort_key

		annotation SummarizationSetBy = Automatic

	column tool_row_label
		dataType: string
		lineageTag: d9cd94a0-a2ce-4d53-b64b-194091dfc05e
		summarizeBy: none
		sourceColumn: tool_row_label
		sortByColumn: tool_sort_key

		annotation SummarizationSetBy = Automatic

	partition tbl_tools = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(
				        File.Contents(#"cv_source_path"),
				        null,
				        true
				    ),
				    tbl_tools_Table = Source{[Item = "tbl_tools", Kind = "Table"]}[Data],
				    #"Changed Type" =
				        Table.TransformColumnTypes(
				            tbl_tools_Table,
				            {
				                {"tool_id", Int64.Type},
				                {"tool_group_id", Int64.Type},
				                {"tool_display_name", type text},
				                {"overall_proficiency_level", Int64.Type}
				            }
				        ),
				
				    #"Added tool_sort_key" =
				        Table.AddColumn(
				            #"Changed Type",
				            "tool_sort_key",
				            each (7 - (if [overall_proficiency_level] = null then 0 else [overall_proficiency_level])) * 1000 + [tool_id],
				            Int64.Type
				        ),
				
				    #"Added tool_row_label" =
				        Table.AddColumn(
				            #"Added tool_sort_key",
				            "tool_row_label",
				            each [tool_display_name],
				            type text
				        )
				in
				    #"Added tool_row_label"

	annotation PBI_ResultType = Table

