table tbl_employers
	lineageTag: eb727951-37f0-48ca-8e47-2daed71d2a06

	column employer_id
		dataType: int64
		formatString: 0
		lineageTag: 82575815-030d-4442-bef3-6cd1448a1512
		summarizeBy: none
		sourceColumn: employer_id

		annotation SummarizationSetBy = Automatic

	column employer_name
		dataType: string
		lineageTag: 7d8f59bf-024e-4ff8-81ec-0e0f2a332cf8
		summarizeBy: none
		sourceColumn: employer_name

		annotation SummarizationSetBy = Automatic

	column industry_id
		dataType: int64
		formatString: 0
		lineageTag: c3a96b94-e200-4a37-bb9e-2bd4f1d509f1
		summarizeBy: none
		sourceColumn: industry_id

		annotation SummarizationSetBy = Automatic

	partition tbl_employers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(
				        File.Contents(#"cv_source_path"),
				        null,
				        true
				    ),
				    tbl_employers_Table = Source{[Item = "tbl_employers", Kind = "Table"]}[Data],
				    #"Changed Type" =
				        Table.TransformColumnTypes(
				            tbl_employers_Table,
				            {
				                {"employer_id", Int64.Type},
				                {"employer_name", type text},
				                {"industry_id", Int64.Type}
				            }
				        )
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

