table tbl_additional
	lineageTag: 589a1a69-0331-4583-ac61-5d53bdcbb5fe

	column additional_id
		dataType: int64
		formatString: 0
		lineageTag: dc5d2641-61ae-4e8d-aa7f-49610dc5a6e9
		summarizeBy: none
		sourceColumn: additional_id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 08592b34-f305-43ef-998d-15581bc91132
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column detail
		dataType: string
		lineageTag: 9ad401e2-0c88-4af2-a3ba-11fa6e933c73
		summarizeBy: none
		sourceColumn: detail

		annotation SummarizationSetBy = Automatic

	column from_year
		dataType: int64
		formatString: 0
		lineageTag: d37d7c85-7480-44f9-be45-c9deb546f01a
		summarizeBy: none
		sourceColumn: from_year

		annotation SummarizationSetBy = Automatic

	column to_year
		dataType: int64
		formatString: 0
		lineageTag: 3d18f2c9-a408-4bec-b25a-57fc694a1247
		summarizeBy: none
		sourceColumn: to_year

		annotation SummarizationSetBy = Automatic

	column section
		dataType: string
		lineageTag: 73fe11dd-ac8a-4efc-8310-b85cad9884d7
		summarizeBy: none
		sourceColumn: section

		annotation SummarizationSetBy = Automatic

	column section_order
		dataType: int64
		formatString: 0
		lineageTag: 55af791a-4f05-4df1-b1c1-7f54cf66a42f
		summarizeBy: none
		sourceColumn: section_order

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 06f6aee8-d896-4290-9e5d-804ba390269a
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column is_highlight
		dataType: boolean
		lineageTag: 1c4a1cb7-8a38-414f-b54e-b26c8c49acf1
		summarizeBy: none
		sourceColumn: is_highlight

		annotation SummarizationSetBy = Automatic

	partition tbl_additional = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(
				        File.Contents(#"cv_source_path"),
				        null,
				        true
				    ),
				    tbl_additional_Table = Source{[Item = "tbl_additional", Kind = "Table"]}[Data],
				    #"Changed Type" =
				        Table.TransformColumnTypes(
				            tbl_additional_Table,
				            {
				                {"additional_id", Int64.Type},
				                {"section", type text},
				                {"section_order", Int64.Type},
				                {"title", type text},
				                {"detail", type text},
				                {"from_year", Int64.Type},
				                {"to_year", Int64.Type},
				                {"url", type text},
				                {"is_highlight", type logical}
				            }
				        )
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

