table tbl_project_tool
	lineageTag: c1669aa6-72f5-49b5-855c-fcdcbbf2cf39

	column project_tool_id
		dataType: int64
		formatString: 0
		lineageTag: c6fd09a1-82f8-4b10-9473-785549cd54eb
		summarizeBy: none
		sourceColumn: project_tool_id

		annotation SummarizationSetBy = Automatic

	column project_id
		dataType: int64
		formatString: 0
		lineageTag: a081aea4-6858-484d-a953-6dc4862afb66
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column tool_id
		dataType: int64
		formatString: 0
		lineageTag: b051acc9-4206-4b71-81dd-8b874aa879de
		summarizeBy: none
		sourceColumn: tool_id

		annotation SummarizationSetBy = Automatic

	column context_relevance_level
		dataType: int64
		formatString: 0
		lineageTag: 70a96f69-4283-48b8-b610-435ec881c221
		summarizeBy: none
		sourceColumn: context_relevance_level

		annotation SummarizationSetBy = Automatic

	partition tbl_project_tool = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(
				        File.Contents(#"cv_source_path"),
				        null,
				        true
				    ),
				    tbl_project_tool_Table = Source{[Item = "tbl_project_tool", Kind = "Table"]}[Data],
				    #"Changed Type" =
				        Table.TransformColumnTypes(
				            tbl_project_tool_Table,
				            {
				                {"project_tool_id", Int64.Type},
				                {"project_id", Int64.Type},
				                {"tool_id", Int64.Type},
				                {"context_relevance_level", Int64.Type}
				            }
				        )
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

